### ISSUE TITLE
Yum update cache and Upgrade packages in one 

### ISSUE THREAD

**Issue by kdpuvvadi** [kdpuvvadi/Nginx-Proxy-Manager-Ansible#3]
yum cache update & package upgrades are on separate tasks. combine them with following 

```
- name: yum cache update & upgrade
  yum: 
    name: "*"
    state: latest
    update_cache: true
  when:
    - ansible_facts.os_family == "RedHat"
```
